"""
Base strategy interface for HFT scalping strategies.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional

import numpy as np
import pandas as pd


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    direction: int  # 1 = long, -1 = short, 0 = no signal
    stop_loss: float = 0.0  # Absolute price for stop loss
    take_profit: float = 0.0  # Absolute price for take profit
    strength: float = 1.0  # Signal strength (0-1)


@dataclass
class StrategyConfig:
    """Base configuration for strategies."""
    name: str = "base"
    # Time filter - only trade during high-volatility hours (UTC)
    active_hours: list = field(default_factory=lambda: list(range(24)))
    # Minimum bars before strategy starts generating signals (warmup)
    warmup_period: int = 20


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    def __init__(self, config: Optional[dict] = None):
        self.config = config or {}
        self.name = self.config.get("name", self.__class__.__name__)

    @abstractmethod
    def generate_signals(self, bars: pd.DataFrame) -> np.ndarray:
        """
        Generate trading signals from bar data.

        Parameters
        ----------
        bars : pd.DataFrame
            OHLC bars with columns: open, high, low, close, tick_count, volume,
            avg_spread, max_spread, range, returns, log_returns

        Returns
        -------
        np.ndarray
            Array of shape (n_bars, 3) where columns are:
            [signal_direction, stop_loss_distance, take_profit_distance]
            signal_direction: 1 = buy, -1 = sell, 0 = no signal
            stop_loss_distance: distance in points from entry
            take_profit_distance: distance in points from entry
        """
        pass

    def get_default_params(self) -> dict:
        """Return default parameters for this strategy."""
        return self.config.copy()

    def get_param_grid(self) -> dict:
        """Return parameter grid for optimization."""
        return {}
